# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - release
  - devel
  - bioc-release

warnings_are_errors: false

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual

addons:
  apt:
    packages:
      - libnetcdf-dev
